Repository Multiwoven/helm-charts, pull requests merged in 2024-10, with the labels that each got.

#46 Feature remove acme challenge resources
  charts/multiwoven/Chart.yaml
  charts/multiwoven/values.yaml
Labels: enhancement, deploy-to-staging, configuration changes, Review effort [1-5]: 1

#48 chore: add user verification env
  charts/multiwoven/Chart.yaml
  charts/multiwoven/templates/multiwoven-config.yaml
  charts/multiwoven/values.yaml
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#49 feat: exposing worker health endpoint
  .github/workflows/deploy-staging.yml
  .github/workflows/lint-test.yml
  charts/multiwoven/Chart.yaml
  charts/multiwoven/templates/multiwoven-ingress.yaml
  charts/multiwoven/templates/multiwoven-worker-service.yaml
  charts/multiwoven/values.yaml
Labels: enhancement, deploy-to-staging, Review effort [1-5]: 2, configuration changes

#50 fix: learned today that the warning about the useless regex in the pa…
  charts/multiwoven/templates/multiwoven-ingress.yaml
Labels: deploy-to-staging
